### ISSUE TITLE
Support for python ver 3.8

### ISSUE THREAD

**Issue by ParamB11** [automl/CARL#104]
Hi, 

I am trying to use tf-agents and CARL together on gpu and to make sure everything is compatible I am using python=3.8, tensorflow=2.3, tf-agents=0.6.0. But CARL doesn't work with python=3.8. If you could give support for python ver 3.8 that would be great.

**Comment by benjamc** [comment]
Hi, 
in theory, CARL should work with python 3.8. You can update this [line](https://github.com/automl/CARL/blob/e9240755bdc42b0924d1cf2db61983a555013342/setup.py#L76)     `python_requires=">=3.9",` and change the 9 to an 8 and check if it works.
