### ISSUE TITLE
Inquiry Regarding RL Libraries and Curves in CARL Project

### ISSUE THREAD

**Issue by BorisGuo6** [automl/CARL#105]
Hello CARL Team,

I hope this message finds you well. I am currently exploring the CARL project and came across your paper. I have a couple of questions regarding the implementation details mentioned in your paper as well as the curve generation on the CARL website.

1. In your paper, you reference the use of an RL code library for your experiments. Could you please specify which RL code library you used for the experiments described in the paper? This information would be valuable for those interested in replicating your results.

2. Additionally, I noticed the presence of curves on the CARL website, particularly on this page: [https://automl.github.io/CARL/main/source/environments/environment_families/classic_control.html](https://automl.github.io/CARL/main/source/environments/environment_families/classic_control.html). Could you kindly clarify which RL library or framework was used to generate these curves? Understanding the underlying RL library would assist users in better comprehending the provided visualizations.

I appreciate your assistance in providing this information, as it will contribute to a deeper understanding of your work and the CARL project as a whole.

Thank you for your time and consideration.

**Comment by amsks** [comment]
Hey,

I am not sure what you mean by the code library. If you are referring to the code library for reproducing the experiments, you can check out the train branch, where we have the instructions for replicating the experiment. Additionally, all the auxiliary libraries required to reproduce the experiments are the setup for creating the conda environment.

**Comment by TheEimer** [comment]
Closed due to staleness, feel free to ping to reopen
