### ISSUE TITLE
CARLLunarLander not training properly

### ISSUE THREAD

**Issue by ParamB11** [automl/CARL#106]
Hi,

I have been using CARL with tensorflow agents to test some things. Everything was working fine until I updated from CARL version 0.2.0 to 1.0.0. After this update training on CARLLunarLander would not lead to good performance. I was able to replicate similar behavior with stable baselines PPO agent and the code for the same is below.
```from functools import partial

import gymnasium
from gymnasium.wrappers import FlattenObservation

from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.evaluation import evaluate_policy

from carl.envs import CARLLunarLander

def env_fn():
    return FlattenObservation(CARLLunarLander())

vec_env_ll = make_vec_env(env_fn, n_envs=16)
ppo_agent = PPO("MlpPolicy", vec_env_ll, verbose=1)

ppo_agent.learn(total_timesteps=1e6)

mean_reward, std_reward = evaluate_policy(ppo_agent, ppo_agent.get_env(), n_eval_episodes=100)
print("Reward: Mean = {0}, Standard deviation = {1}".format(mean_reward, std_reward))
# Output: Reward: Mean = -130.27439046, Standard deviation = 45.32413066301294

env_fn_gymn = partial(
    gymnasium.make, "LunarLander-v2"
)
vec_env_gymn = make_vec_env(env_fn_gymn, n_envs=16)
ppo_agent2 = PPO("MlpPolicy", vec_env_gymn, verbose=1)

ppo_agent2.learn(total_timesteps=1e6)

mean_reward, std_reward = evaluate_policy(ppo_agent2, ppo_agent2.get_env(), n_eval_episodes=100)
print("Reward: Mean = {0}, Standard deviation = {1}".format(mean_reward, std_reward))
# Output: Reward: Mean = 261.80816654, Standard deviation = 38.24869197512363
```
The expected behavior is that the reward obtained by training on CARLLunarLander and gymnasium.make("LunarLander-v2") should be close to each other since they are identical environments. However the same is not happening.
The jupyter notebook with the code and more details is [here](https://colab.research.google.com/drive/1J147QeKgvCONeP-eswfy_5uocQiPWQA1?usp=sharing).

PS: Similar behavior can be seen with tensorflow agents PPO agent.

Thanks.

**Comment by benjamc** [comment]
Hi,
my first guess would be that the CARLLunarLander has a larger state space containing the classic state vector and the context features. In our experiments we saw that concatenating the context to the state sometimes lead to detrimental performance. Maybe this is also the case?

**Comment by ParamB11** [comment]
Yeah, that was the problem. Thanks.
