### ISSUE TITLE
Subtle error in action_space type for dm_control (gym/gymnasium)

### ISSUE THREAD

**Issue by sai-prasanna** [automl/CARL#109]
In the codebase we first wrap dmcontrol environments into gym, with `MujocoToGymWrapper`. But when we again wrap them into gymnasium, we don't cast the action_space (and possibly other stuff) into corresponding gymnasium's spaces class. I guess making `MujocoToGymWrapper` use gymnasium instead of gym would fix this problem.

**Comment by TheEimer** [comment]
This is now fixed on the development branch and should come to main soon as well
