### ISSUE TITLE
AttributeError: 'System' object has no attribute 'body_idx' in brax

### ISSUE THREAD

**Issue by andy-james0310** [automl/CARL#45]
when running test/test_all_envs.py, there is AttributeError: 'System' object has no attribute 'body_idx' in carl_fetch and carl_humanoid environments.

**Comment by benjamc** [comment]
Do you mean in this line?
[        self.env.target_idx = self.env.sys.body.index["Target"]](https://github.com/automl/CARL/blob/6c0ff927d30305709d55605eb8f7eae2754d0005/carl/envs/brax/carl_fetch.py#L106)

If so, do you have the newest version of CARL?

Best wishes
:sun_with_face:

**Comment by andy-james0310** [comment]
Thanks. The newest version has no this problem.

But, there is another problem when running the environments of Brax.

WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)

raise TypeError("len() of unsized object") from err  # same as numpy error
TypeError: len() of unsized object

There is no problem in classic_control environments

**Comment by benjamc** [comment]
Could you provide a minimal working example for this error and/or explaining more, when that happens?

**Comment by TheEimer** [comment]
I'll close this since there was no further example given. If anything else comes up, please open a new issue
