### ISSUE TITLE
Documentation cannot be accessed

### ISSUE THREAD

**Issue by GilgameshD** [automl/CARL#75]
the link to the documentation cannot be found: https://carl.readthedocs.io/en/latest/

**Comment by TheEimer** [comment]
Sorry this hasn't been answered yet, I'm not 100% sure what's going on either. @benjamc did we move to GitHub pages and the link simply wasn't updated? Because I can't find a GitHub page workflow either...

**Comment by TheEimer** [comment]
Should be resolved at this point, pages are building correctly via workflow
