### ISSUE TITLE
About brax

### ISSUE THREAD

**Issue by ReedZyd** [automl/CARL#81]
Hello, the version of brax and the main brach seems to be not matched, I can not import '_SYSTEM_CONFIG' from brax.envs.ant. 

In `carl/envs/brax/carl_ant.py`: from brax.envs.ant import _SYSTEM_CONFIG, Ant

**Comment by benjamc** [comment]
Hi ReedZyd,
thanks for pointing that out!
We updated the package requirements and restricted the brax version to 0.0.16 for now (#83 ).
