### ISSUE TITLE
Dataset Folders for CARLRNA

### ISSUE THREAD

**Issue by benjamc** [automl/CARL#9]
Provide option to specify several folders containing a dataset each instead of a single path like it is right now

**Comment by TheEimer** [comment]
Is this resolved by the RNA PR @amsks ?

**Comment by amsks** [comment]
Currently, each shell script makes separate dataset folders under the ```data/``` directory. This seems to address this issue, but based on the description above, I am not sure. Can this please be elaborated upon?

**Comment by TheEimer** [comment]
I thiknn this might be about the datapath at env creation? Also not sure, though - @benjamc ?

**Comment by benjamc** [comment]
Not relevant anymore
